version: 1.3 b{build}
image: Visual Studio 2022
configuration:
- ReleaseCefSharp
- ReleaseSelenium
environment:
  sonarcloud_apikey:
    secure: Jo/wJPpRU9pQYuIdI7bwCZV2ie7BZI54BTkbVX9Zkcugeb6LxVgP9tpF6bM2J3d4
  JAVA_HOME: C:\Program Files\Java\jdk17
platform:
- x64
build_script:
- set PATH=%JAVA_HOME%\bin;%PATH%
- dotnet tool install --global dotnet-sonarscanner
- dotnet sonarscanner begin /o:"scottjsh" /k:"scottjsh_AutoKkutu" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login=%sonarcloud_apikey%
- nuget restore
- dotnet restore
- dotnet publish /verbosity:normal "AutoKkutuGui/AutoKkutuGui.csproj" --no-self-contained -c %CONFIGURATION%  -a %PLATFORM% -o "publish/%CONFIGURATION%.%PLATFORM%"
- dotnet sonarscanner end /d:sonar.login=%sonarcloud_apikey%
- 7z a -t7z -ms=on -mqs -slp -bt -bb3 -bsp1 -sae -m0=LZMA2 -mx=9 -myx=9 -md=128m -mfb=273 -mmt=8 -- "Windows.%PLATFORM%.%CONFIGURATION%.7z" "%APPVEYOR_BUILD_FOLDER%\publish\%CONFIGURATION%.%PLATFORM%"
artifacts:
- path: Windows.%PLATFORM%.%CONFIGURATION%.7z
